name = "workers-test"
main = "src/index.js"
compatibility_date = "2024-01-01"

# We use 'routes' (plural) to intercept traffic to your existing PHP site
routes = [
	{ pattern = "empty.svcover.nl/*", zone_name = "svcover.nl" }
]